on: 
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - SF1200
        - SF1200
        - AXT1800
      sourcecode:
        description: 'Source code URL'     
        required: true
      pkgname:
        description: 'Openwrt package name'  
        required: true
        
jobs:
  setpackage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: build ipk
      id: build
      env:
        SOURCECODEURL: ${{ github.event.inputs.sourcecode }}
        PKGNAME: ${{ github.event.inputs.pkgname }}
        BOARD: ${{ github.event.inputs.device }}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./build.sh
        ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.pkgname }}_related_ipks
        path: |
          ./*ipk*
