on: 
  workflow_dispatch:
    inputs:
      sourcecode:
        description: 'Source code URL'     
        required: true
      pkgname:
        description: 'Openwrt package name'  
        required: true
        
jobs:
  setpackage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        SOURCECODEURL: ${{ github.event.inputs.sourcecode }}
        PKGNAME: ${{ github.event.inputs.pkgname }}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./build.sh
        ./build.sh
    - name: Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: "*.ipk"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
